-- ─────────────────────────────────────────────────────────────────────────────
-- Migración 040 — Muestras F6: vínculo formal muestra aprobada ↔ proyecto
-- ─────────────────────────────────────────────────────────────────────────────
-- Cuando INGENIERIA aprueba una muestra, queremos registro inmutable que
-- "esta especificación quedó aprobada para este proyecto". Snapshot de los
-- datos clave (código, descripción, tipo) para que sobrevivan a cambios
-- futuros en la muestra original, y referencia al PDF de sample request más
-- reciente como "spec firmada".
--
-- Una row por (muestra, versión) — UNIQUE constraint. Si una V2 también
-- se aprueba, queda otro row separado para ese mismo proyecto+muestra.
--
-- Reglas de borrado:
--   - proyecto borrado → CASCADE (no nos sirve la aprobación sin proyecto)
--   - muestra borrada → CASCADE (mismo motivo)
--   - archivo PDF borrado → SET NULL (la aprobación queda histórica, solo
--     pierde el link al PDF)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.proyectos_muestras_aprobadas (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id       integer NOT NULL REFERENCES public.proyectos(id) ON DELETE CASCADE,
  muestra_id        integer NOT NULL REFERENCES public.muestras(id)  ON DELETE CASCADE,
  version_numero    integer NOT NULL,
  -- Snapshot al momento de la aprobación
  codigo            text NOT NULL,
  descripcion       text NOT NULL,
  tipo              public.muestra_tipo NOT NULL,
  -- PDF más reciente de tipo='sample_request' para la versión aprobada
  pdf_archivo_id    integer REFERENCES public.muestras_archivos(id) ON DELETE SET NULL,
  -- Metadatos
  fecha_aprobacion  date NOT NULL DEFAULT CURRENT_DATE,
  aprobado_por      uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
  notas             text,
  created_at        timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT proyectos_muestras_aprobadas_unq UNIQUE (muestra_id, version_numero)
);

COMMENT ON TABLE public.proyectos_muestras_aprobadas IS
  'Registro inmutable de muestras aprobadas vinculadas a un proyecto. Una row por (muestra, versión). F6 Muestras 2026-06-09.';

-- Índices para queries comunes
CREATE INDEX IF NOT EXISTS idx_proyectos_muestras_aprobadas_proyecto
  ON public.proyectos_muestras_aprobadas (proyecto_id, fecha_aprobacion DESC);

CREATE INDEX IF NOT EXISTS idx_proyectos_muestras_aprobadas_muestra
  ON public.proyectos_muestras_aprobadas (muestra_id);
